
import React, { useState, useEffect } from 'react';
import { generateSmartQuiz } from '../../services/geminiService';
import Loader from '../common/Loader';

interface Option {
    text: string;
    isCorrect: boolean;
    feedback: string;
}

interface Question {
    id: number;
    question: string;
    options: Option[];
    difficulty: string;
    type: string;
}

interface QuizData {
    title: string;
    questions: Question[];
    summary: {
        perfectMessage: string;
        goodMessage: string;
        averageMessage: string;
    };
}

interface SmartQuizGeneratorProps {
    onShare: (options: { contentText: string; contentType: 'text' }) => void;
}

const SmartQuizGenerator: React.FC<SmartQuizGeneratorProps> = ({ onShare }) => {
    const [mode, setMode] = useState<'topic' | 'content'>('topic');
    const [input, setInput] = useState('');
    const [quizData, setQuizData] = useState<QuizData | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Game State
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [selectedOptionIndex, setSelectedOptionIndex] = useState<number | null>(null);
    const [isAnswered, setIsAnswered] = useState(false);
    const [score, setScore] = useState(0);
    const [streak, setStreak] = useState(0);
    const [maxStreak, setMaxStreak] = useState(0);
    const [gameState, setGameState] = useState<'setup' | 'playing' | 'finished'>('setup');

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!input.trim()) {
            setError('Please enter a topic or paste content.');
            return;
        }
        setLoading(true);
        setError(null);
        
        try {
            const response = await generateSmartQuiz(input, mode === 'topic');
            const data: QuizData = JSON.parse(response.text);
            
            if (!data.questions || data.questions.length === 0) {
                throw new Error("No questions generated.");
            }

            setQuizData(data);
            setGameState('playing');
            setCurrentQuestionIndex(0);
            setScore(0);
            setStreak(0);
            setMaxStreak(0);
            setIsAnswered(false);
            setSelectedOptionIndex(null);
        } catch (err) {
            console.error(err);
            setError('Failed to generate quiz. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleOptionClick = (index: number) => {
        if (isAnswered) return;
        
        setSelectedOptionIndex(index);
        setIsAnswered(true);
        
        const isCorrect = quizData!.questions[currentQuestionIndex].options[index].isCorrect;
        
        if (isCorrect) {
            setScore(s => s + 1);
            setStreak(s => {
                const newStreak = s + 1;
                setMaxStreak(ms => Math.max(ms, newStreak));
                return newStreak;
            });
        } else {
            setStreak(0);
        }
    };

    const handleNextQuestion = () => {
        if (currentQuestionIndex < (quizData?.questions.length || 0) - 1) {
            setCurrentQuestionIndex(prev => prev + 1);
            setIsAnswered(false);
            setSelectedOptionIndex(null);
        } else {
            setGameState('finished');
        }
    };

    const getResultMessage = () => {
        if (!quizData) return '';
        const percentage = (score / quizData.questions.length) * 100;
        if (percentage === 100) return quizData.summary.perfectMessage;
        if (percentage >= 70) return quizData.summary.goodMessage;
        return quizData.summary.averageMessage;
    };

    const shareResults = () => {
        if (!quizData) return;
        const text = `I just scored ${score}/${quizData.questions.length} on the "${quizData.title}" quiz! 🎯\nMax Streak: ${maxStreak} 🔥\n\nGenerated by AI Creative Suite.`;
        onShare({ contentText: text, contentType: 'text' });
    };

    const resetQuiz = () => {
        setGameState('setup');
        setQuizData(null);
        setInput('');
    };

    if (gameState === 'setup') {
        return (
            <div className="max-w-3xl mx-auto">
                <div className="bg-gradient-to-r from-indigo-900 to-purple-900 rounded-2xl p-8 border border-indigo-700 text-center mb-8 shadow-xl">
                    <h2 className="text-3xl font-bold text-white mb-2 flex justify-center items-center gap-3">
                        <span className="text-4xl">🧠</span> Smart Quiz Generator
                    </h2>
                    <p className="text-indigo-200">Turn any text, document, or topic into a gamified learning experience instantly.</p>
                </div>

                <div className="bg-slate-900/50 p-6 rounded-2xl border border-slate-800">
                    <div className="flex bg-slate-800 rounded-lg p-1 mb-6">
                        <button 
                            onClick={() => setMode('topic')}
                            className={`flex-1 py-2 px-4 rounded-md text-sm font-bold transition ${mode === 'topic' ? 'bg-purple-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                        >
                            From Topic (Web Search)
                        </button>
                        <button 
                            onClick={() => setMode('content')}
                            className={`flex-1 py-2 px-4 rounded-md text-sm font-bold transition ${mode === 'content' ? 'bg-purple-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                        >
                            Paste Content
                        </button>
                    </div>

                    <form onSubmit={handleGenerate} className="space-y-4">
                        {mode === 'topic' ? (
                            <div>
                                <label className="block text-sm font-medium text-slate-300 mb-2">Enter a Topic</label>
                                <input 
                                    type="text" 
                                    value={input} 
                                    onChange={(e) => setInput(e.target.value)}
                                    placeholder="e.g., Quantum Physics, History of Rome, JavaScript Basics"
                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-4 text-white focus:ring-2 focus:ring-purple-500 transition"
                                />
                            </div>
                        ) : (
                            <div>
                                <label className="block text-sm font-medium text-slate-300 mb-2">Paste Text Content</label>
                                <textarea 
                                    value={input} 
                                    onChange={(e) => setInput(e.target.value)}
                                    placeholder="Paste article text, notes, or documentation here..."
                                    rows={8}
                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-4 text-white focus:ring-2 focus:ring-purple-500 transition resize-none"
                                />
                            </div>
                        )}

                        <button 
                            type="submit" 
                            disabled={loading}
                            className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white font-bold py-4 rounded-xl transition transform hover:scale-[1.02] disabled:opacity-50 disabled:transform-none flex justify-center items-center gap-2 shadow-lg shadow-purple-900/20"
                        >
                            {loading ? <Loader /> : <span>✨ Generate Quiz</span>}
                        </button>
                        {error && <p className="text-red-400 text-center text-sm bg-red-900/20 p-2 rounded">{error}</p>}
                    </form>
                </div>
            </div>
        );
    }

    if (gameState === 'playing' && quizData) {
        const question = quizData.questions[currentQuestionIndex];
        const progress = ((currentQuestionIndex + 1) / quizData.questions.length) * 100;

        return (
            <div className="max-w-2xl mx-auto">
                {/* Header Stats */}
                <div className="flex justify-between items-center mb-6 bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                    <div className="flex items-center gap-2">
                        <span className="text-2xl">🏆</span>
                        <div>
                            <p className="text-xs text-slate-400 uppercase font-bold">Score</p>
                            <p className="text-xl font-bold text-white">{score}</p>
                        </div>
                    </div>
                    <div className="flex-grow mx-8">
                        <div className="flex justify-between text-xs text-slate-400 mb-1">
                            <span>Question {currentQuestionIndex + 1} / {quizData.questions.length}</span>
                            <span>{Math.round(progress)}%</span>
                        </div>
                        <div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden">
                            <div className="bg-gradient-to-r from-blue-500 to-purple-500 h-full transition-all duration-500" style={{ width: `${progress}%` }}></div>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        <div className="text-right">
                            <p className="text-xs text-slate-400 uppercase font-bold">Streak</p>
                            <p className="text-xl font-bold text-orange-400">{streak}</p>
                        </div>
                        <span className="text-2xl">🔥</span>
                    </div>
                </div>

                {/* Question Card */}
                <div className="bg-slate-900 rounded-2xl border border-slate-700 overflow-hidden shadow-2xl relative">
                    {/* Difficulty Badge */}
                    <div className="absolute top-4 right-4 px-3 py-1 rounded-full text-xs font-bold bg-slate-800 border border-slate-600 text-slate-300">
                        {question.difficulty} • {question.type}
                    </div>

                    <div className="p-8">
                        <h3 className="text-xl md:text-2xl font-bold text-white mb-8 leading-relaxed">
                            {question.question}
                        </h3>

                        <div className="space-y-3">
                            {question.options.map((option, idx) => {
                                let buttonStyle = "bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-200"; // Default
                                if (isAnswered) {
                                    if (option.isCorrect) buttonStyle = "bg-green-900/40 border-green-500 text-green-100"; // Correct answer
                                    else if (idx === selectedOptionIndex) buttonStyle = "bg-red-900/40 border-red-500 text-red-100"; // Wrong selection
                                    else buttonStyle = "bg-slate-800/50 border-slate-700 text-slate-500"; // Unselected
                                }

                                return (
                                    <button
                                        key={idx}
                                        onClick={() => handleOptionClick(idx)}
                                        disabled={isAnswered}
                                        className={`w-full p-4 rounded-xl border-2 text-left font-semibold transition-all duration-200 flex items-center justify-between ${buttonStyle}`}
                                    >
                                        <span>{option.text}</span>
                                        {isAnswered && option.isCorrect && <span className="text-green-400 text-xl">✓</span>}
                                        {isAnswered && idx === selectedOptionIndex && !option.isCorrect && <span className="text-red-400 text-xl">✗</span>}
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    {/* Feedback Area */}
                    {isAnswered && (
                        <div className={`p-6 border-t ${quizData.questions[currentQuestionIndex].options[selectedOptionIndex!].isCorrect ? 'bg-green-900/20 border-green-900' : 'bg-red-900/20 border-red-900'}`}>
                            <h4 className={`font-bold mb-1 ${quizData.questions[currentQuestionIndex].options[selectedOptionIndex!].isCorrect ? 'text-green-400' : 'text-red-400'}`}>
                                {quizData.questions[currentQuestionIndex].options[selectedOptionIndex!].isCorrect ? 'Correct! 🎉' : 'Not quite...'}
                            </h4>
                            <p className="text-slate-300 text-sm mb-4">
                                {quizData.questions[currentQuestionIndex].options[selectedOptionIndex!].feedback}
                            </p>
                            <button 
                                onClick={handleNextQuestion}
                                className="w-full bg-slate-100 hover:bg-white text-slate-900 font-bold py-3 rounded-lg transition shadow-lg"
                            >
                                {currentQuestionIndex < quizData.questions.length - 1 ? 'Next Question →' : 'See Results →'}
                            </button>
                        </div>
                    )}
                </div>
            </div>
        );
    }

    if (gameState === 'finished' && quizData) {
        const percentage = Math.round((score / quizData.questions.length) * 100);
        
        return (
            <div className="max-w-2xl mx-auto text-center">
                <div className="bg-slate-900 rounded-3xl border border-slate-700 p-10 shadow-2xl">
                    <div className="text-6xl mb-4 animate-bounce">
                        {percentage === 100 ? '🏆' : percentage >= 70 ? '🌟' : '🎓'}
                    </div>
                    <h2 className="text-3xl font-bold text-white mb-2">Quiz Complete!</h2>
                    <p className="text-slate-400 mb-8">{getResultMessage()}</p>

                    <div className="grid grid-cols-3 gap-4 mb-8">
                        <div className="bg-slate-800 p-4 rounded-xl">
                            <p className="text-slate-400 text-xs uppercase font-bold">Score</p>
                            <p className="text-2xl font-bold text-white">{score}/{quizData.questions.length}</p>
                        </div>
                        <div className="bg-slate-800 p-4 rounded-xl">
                            <p className="text-slate-400 text-xs uppercase font-bold">Accuracy</p>
                            <p className={`text-2xl font-bold ${percentage >= 70 ? 'text-green-400' : 'text-yellow-400'}`}>{percentage}%</p>
                        </div>
                        <div className="bg-slate-800 p-4 rounded-xl">
                            <p className="text-slate-400 text-xs uppercase font-bold">Max Streak</p>
                            <p className="text-2xl font-bold text-orange-400">{maxStreak} 🔥</p>
                        </div>
                    </div>

                    <div className="flex flex-col gap-3">
                        <button 
                            onClick={shareResults}
                            className="w-full bg-purple-600 hover:bg-purple-500 text-white font-bold py-3 px-6 rounded-xl transition shadow-lg shadow-purple-900/30 flex items-center justify-center gap-2"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path d="M15 8a3 3 0 10-2.977-2.63l-4.94 2.47a3 3 0 100 4.319l4.94 2.47a3 3 0 10.895-1.789l-4.94-2.47a3.027 3.027 0 000-.74l4.94-2.47C13.456 7.68 14.19 8 15 8z" /></svg>
                            Share Results
                        </button>
                        <button 
                            onClick={resetQuiz}
                            className="w-full bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold py-3 px-6 rounded-xl transition border border-slate-600"
                        >
                            Create Another Quiz
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return null;
};

export default SmartQuizGenerator;
